### ISSUE TITLE
Put the library on Maven Central repository 

### ISSUE THREAD

**Issue by aleroot** [threadly/auroraArc#12]
I don't think that the library is available on the maven central repository, that would simplify the deployment of applications using it .

**Comment by jentfoo** [comment]
All non-`SNAPSHOT` versions of threadly projects are already in maven central:

http://search.maven.org/#search%7Cga%7C1%7Cthreadly

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.threadly%22%20AND%20a%3A%22auroraArc%22

I went ahead and added the coordinates to the README so that they are easier to find in the future.
