### ISSUE TITLE
Add PostgreSQL compatibility 

### ISSUE THREAD

**Issue by aleroot** [threadly/auroraArc#15]
Amazon Aurora can be now configured with PostgreSQL backend, so it would be useful to have this driver compatible with it ...

**Comment by jentfoo** [comment]
We have already been moving to allowing the user to plug in the driver.  Using the postgres driver should be fairly easily.  Here are some considerations that have kept me from moving forward with this more (maybe if anyone has any ideas on these, they can let me know):
* Is it reasonable for people to know they will need to specify two dependencies?  This one, as well as some other driver to delegate to.
* How do we handle determining what driver to delegate to.  Particularly because the dependent driver may not have been registered in `java.sql.DriverManager`.  Or we could require people to make sure their desired driver is loaded (typically done by `Class.forName` before using our driver).
* Alternatively maybe we could do this by calling into the driver / library itself.  This may require the special knowledge that additional work is needed with this driver before it is usable (particularly if it does not come with a delegate driver out of the box included).

But yeah, we just need to figure out how the user experience is for adding in their driver of choice, but the code is already well setup for changing out the driver.  If you have any thoughts let me know.  Also let me know how valuable this would be to you, and I can try to prioritize this work forward.

**Comment by aleroot** [comment]
Yeah, I think that is reasonable for a user to specify auroraArc dependency together with their database driver dependency, it is enough to document it clearly and I don't think it will be a big issue. 
Even the driver registration could be delegated to the user... The auroraArc component should use a driver that is already registered.

**Comment by jentfoo** [comment]
@aleroot I am releasing `auroraArc-psql:0.6` right now (should be available in maven central shortly).  Give it a try and let me know if you have any issues or suggestions (should be plug and play).  Since we are not `1.X` yet, changes are still possible.

**Comment by jentfoo** [comment]
Well I added it, but it's broken (see #18 ).  I will try to get a solution to this and a couple other issues soonish (hopefully sooner than later now that a few other things have calmed down).
