### ISSUE TITLE
Avoid master/slave check in AuroraClusterMonitor when cluster and cluster-ro are configured

### ISSUE THREAD

**Issue by aleroot** [threadly/auroraArc#4]
Since aurora now have implemented two cluster endpoints one for master and the second for read-only(see [here for more information](https://aws.amazon.com/blogs/aws/new-reader-endpoint-for-amazon-aurora-load-balancing-higher-availability/)) we could configure these two URLS and avoid repeatedly checking for server role in `AuroraClusterMonitor` component, because we can be sure that the two URLs will preserve roles. 
Doing these change the logic will be a lot simplified and we will let aurora manage the slave selection automatically. I think that will be useful in most cases to configure the delegation in this simpler way.

**Comment by jentfoo** [comment]
I have not spent any time investigating this feature yet, but I am not sure if it really makes sense to use something like that with this driver (but it might).

I know that the cluster endpoint that points to the `master` server will failover by using slow DNS failover.  The primary goal of this driver is to provide faster failover than DNS could ever provide.

So I am unsure if the secondary failover mechanism also uses DNS or if it has an actual load balancer handling failover conditions?  And then similarly if it is using a load balancer and DNS is not an issue, how do we handle updating our primary server in a manner that can be faster than DNS?

These very much may not be actual problems, as I have not investigated this mechanism at all.  But I would suggest looking into that first before we put any code down.

I did go ahead and move the TODO notes from the README to issues so they can be referenced.  As discussed in email, there is the enhancement which is now captured as #5.  I guess we should consider that if we implemented #5, what capabilities a feature like this might additionally give us.  My intuition is that we can do a better job in the driver if we do the work, but amazon is struggling to get these features to be fully utilized because of lack of driver support.  But I don't honestly know till we investigate further.

**Comment by jentfoo** [comment]
So having thought about this more, I am just going to close this in favor of #5 

It does seem that the secondary read only endpoint is a at least distributed across the members.  I am sure you could produce a solid implementation of a driver which uses these endpoints instead.  But I think we have the capabilities of doing even better in this driver with a bit more work.  Having an understanding of individual cluster members can in the future allow better distributing based off load (for like a t2, or in clusters where members don't have the same instance type like #2 would like to provide).  So I think the better solution is to just remove the per-cluster understanding from the user and instead let cluster membership be more dynamic.

So closing this, but only because I think this is captured by other work I already plan to do.  If you think there is anything I am missing let me know!
